### ISSUE TITLE
Your placeholder doesn't work

### ISSUE THREAD

**Issue by Danuk15** [SkinsRestorer/SRPlaceholderAPIExpansion#1]
I decided to download your placeholder. I wrote /papi ecloud download skinsrestorer, but when I wrote /papi parse me %skinsrestorer_getskinnames%, I was shown an internal error. PAPI version: 2.10.9. Version core: Spigot 1.12.2. Version skinsrestorer: 13.8.4. Please help)

**Comment by AlexProgrammerDE** [comment]
> 
> 
> I decided to download your placeholder. I wrote /papi ecloud download skinsrestorer, but when I wrote /papi parse me %skinsrestorer_getskinnames%, I was shown an internal error. PAPI version: 2.10.9. Version core: Spigot 1.12.2. Version skinsrestorer: 13.8.4. Please help)

Sorry for the late response. Its `%skinsrestorer_getSkinName%`
